#!/bin/bash
#
# Copyright 2008 by Daniel Gryniewicz <dang@gentoo.org>
#
# Released under the GPL version 2
#
# Script to run kvm
#

#
# This will source a file in ${HOME}/.config/kvm-run, and in the current
# directory called kvm-run.conf in that order.  These files set up account-wide
# defaults, and settings for the current kvm to run, including things like
# networks and drives.

RCFILE="${HOME}/.config/kvm-run"
CONFFILE="${PWD}/kvm-run.conf"

# Set usage output
USAGE="[-h |--help]"
LONGUSAGE="\t-h, --help\n\t\tPrint this help message"

# Standard functions
#source ${HOME}/.scripts/functions.sh
die() {
	echo "$@"
	if [ ! -z "$(declare -F | grep "DFGcleanup")" ]; then
		DFGcleanup "$@"
	fi
	exit 1
}

usage() {
	local myusage;
	if [ -n "${USAGE}" ]; then
		myusage=${USAGE}
	else
		myusage="No usage given"
	fi
	if [ -n "$1" ]; then
		echo "$@"
	fi
	echo ""
	echo "Usage:"
	echo "`basename $0` ${myusage}"
	if [ -n "${LONGUSAGE}" ]; then
		echo -e "${LONGUSAGE}"
	fi
	exit 1
}


# Script name
ME=$(basename $0)

# Parse arguments
ARGS=`getopt -o h --long help -n "${ME}" -- "$@"`

if [ $? != 0 ] ; then
	usage 
fi
eval set -- "$ARGS"

while true ; do
	case "$1" in
		-h|--help) usage; shift ;;
		--) shift ; break ;;
		* ) usage "Invalid argument $1";;
	esac
done

# We want parameters for run
shift 2

# Set up defaults
NETNUM=1
NETTYPE=system-vde
BRIDGETAP=btap0
NICMODEL=
IMGFILE=kvm.img
MEMORY=512
CDROM=
BOOT=
GRAPHICS=
VIRTIO=
MOUSE="-usb -usbdevice tablet"
SOUND=
SMP=

if [ -f ${RCFILE} ]; then
	echo "sourcing ${RCFILE}"
	source ${RCFILE}
fi

if [ -f ${CONFFILE} ]; then
	echo "sourcing ${CONFFILE}"
	source ${CONFFILE}
fi

if [ ! -f "${IMGFILE}" ]; then
	die "No image file ${IMGFILE} found"
fi

if [ -n "${VIRTIO}" ]; then
	DISKCMD="-drive file=${IMGFILE},if=virtio,boot=on"
else
	DISKCMD="-hda ${IMGFILE} "
fi

case "${NETTYPE}" in
	system-vde)
		CMD="kvm -net nic${NICMODEL} -net vde,sock=/var/run/vde.ctl"
		;;
	none)
		CMD="kvm"
		;;
	bridge)
		CMD="kvm -net nic${NICMODEL} -net tap,ifname=${BRIDGETAP}"
		;;
	*)
		die "Unknown NETTYPE ${NETTYPE}"
		;;
esac

${CMD} ${DISKCMD} -m ${MEMORY} ${GRAPHICS} ${MOUSE} ${CDROM} ${BOOT} ${SOUND} ${SMP}
